### ISSUE TITLE
登录bug？

### ISSUE THREAD

**Issue by SummersRay** [jungheil/OpenHelloBadminton#1]
sso自动登录时一直提示超时。
手动登录的话在网页输入密码后终端还是卡住的。

**Comment by aixmoyu** [comment]
前端时间网站api接口改了，暂时没有更新计划。。。欢迎提交pr

**Comment by SummersRay** [comment]
好吧，不过可以提供一下源码吗，我想进行新api适配？

**Comment by aixmoyu** [comment]
看了一下，发现就是域名更改了，已做出修改，关闭该issue
https://github.com/jungheil/OpenHelloBadminton/commit/634a2fbcd610bb19307f2ed4c88ba8548c4cdea5
